name    'chillingchua-supervisor'
version '0.1.0'
source 'https://github.com/ChillingChua/supervisor'
author 'The Chilling Chua'
summary 'Install and configure Supervisord'
description "This puppet module is used to install and configure Supervisord. It also provides a custom define to manage services (apps) using it and can also handle multiple processes and grouping."
project_page 'https://github.com/TracyWebTech/puppet-supervisor'

dependency 'stankevich/python', '>= 1.7.1'
dependency 'puppet/stdlib', '>=4.1.0'

